services:

  web-app3:
    container_name: web-app3
    image: immo-web-app3
    ports:
      - 3000:3000
    environment:
      # just copy from immo-docker-compose staging web-app and remove the SSR url
      NUXT_PUBLIC_API_URL: https://api-analyzing.aktuelle-grundstueckspreise.de
      NUXT_PUBLIC_API_URL_CACHED: https://api-cached-redis.aktuelle-grundstueckspreise.de
      NUXT_PUBLIC_API_URL_PLATFORM: https://api-platform.aktuelle-grundstueckspreise.de
      NUXT_PUBLIC_CANONICAL_HOSTNAME: https://www.aktuelle-grundstueckspreise.de
      NUXT_PUBLIC_BLOCK_SEO_INDEXING: "true"
      NUXT_PUBLIC_GTM_ENABLED: "false"
    restart: always
    build: .
